### ISSUE TITLE
Seccion AYUDA

### ISSUE THREAD

**Issue by Markkos89** [Markkos89/Maresa#27]
- En la base de datos, si no está la sección, hay que agregarla.
- En el html si no está el modal, hay que agregarlo.
- En el controlador, si no está la llamada a mAyuda, hay que agregarla y pasarle el objeto ayuda[0] por parámetros.

Hacer de:
- categoria
- turnos
- contratos
- adicionales 
- codigos hora
- tipos hora

Es importante notificar al usuario cuando una tabla tiene relación con otra tabla más grande. Explicando la situación a nivel usuario, obvio.
Mientras más información le demos, mejor.

**Comment by Markkos89** [comment]
@IsaacMiguel

**Comment by IsaacMiguel** [comment]
Ya agregue el modal a las vistas, la ayuda sus respectivos controladores y las secciones a la base para cada sección.
Sigo con la descripción para cada ayuda del sector al menos a nivel básico de ejemplo y luego si tiene relación con otra tabla.

**Comment by IsaacMiguel** [comment]
Agregue una descripción muy básica de cada sección(que permite realizar y un ejemplo)

**Comment by Markkos89** [comment]
Bárbaro

**Comment by IsaacMiguel** [comment]
Agregue a las descripciones de ayudas las relaciones que tienen solamente entre las que respectan al "Parte Diario" y "Categorías" con Alta Empleados.

**Comment by IsaacMiguel** [comment]
Agregue el modal y controlador de Cargos así como la Ayuda y su descripción en la tabla de la base.
Además agregue las demás ayudas que tienen relación con la sección de alta de Empleados.

**Comment by Markkos89** [comment]
Buenísimo !

**Comment by Markkos89** [comment]
Migue una pregunta, lo que hiciste de la seccion ayuda es SOLAMENTE de estas secciones? :

categoria
turnos
contratos
adicionales
codigos hora
tipos hora

saludos

**Comment by IsaacMiguel** [comment]
Tambien toque la seccion de ayuda de:
Sectores
Lugares

Salutes

**Comment by Markkos89** [comment]
oh, gratzie :+1:

**Comment by Markkos89** [comment]
actualizado en servidor

**Comment by Markkos89** [comment]
actualizado en tabla "Version" para q lo vea el cliente. Listoooooooo! :+1:
